### ISSUE TITLE
 'Pods-environment.h' file not found 

### ISSUE THREAD

**Issue by estock** [CyberAgent/iOS-NBUImagePicker#11]
I am trying run and install the project but I am having some difficulty

I updated CocoaPods, and run a pod install and a pod update
I open the workspace and attempt to compile but get the following error

NBUImagePicker/NBUImagePicker.h:23:9: fatal error: 'Pods-environment.h' file not found
#import "Pods-environment.h"
I'm uncertain exactly what this error means, any help would be greatly appretiated

Thanks

**Comment by rivera-ernesto** [comment]
As you can see [here](https://github.com/CyberAgent/iOS-NBUImagePicker/blob/master/Source/NBUImagePicker.h#L22) this import no longer exists.

Please update to a newer NBUImagePicker release.
