### ISSUE TITLE
memory not release

### ISSUE THREAD

**Issue by jobpassion** [CyberAgent/iOS-NBUImagePicker#12]
before open picker, the app use memory 30m
then open the picker, select one image,then the view push to the filter view
memory use increase to 110m
then click cancel button on the left navigation to dismiss controller view
memory use 100m

the 70m(100m - 30m) memory use will never release.
did some one also had this problem?

**Comment by rivera-ernesto** [comment]
Could you try launching the picker more than once to see if it just keeps growing. Ideally profiling with Instruments.

During the first launch is normal that some internal SDK caching/initialization takes place, thus consuming more memory. This may get released later or on low memory conditions automatically.

As for memory leaks or circular retentions, I think I have checked many times in the past.

**Comment by jobpassion** [comment]
I tried launching the picker more than once, it didn't keep growing.
Because of I'm new to iOS developing, I may try profiling with Instruments
as soon as possible.
I'll try to see that if memory get released later.If I find some useful,
I'll contract you.

Thanks for your replying.
The ImagePicker is wonderful ! Thanks for your effort for that.

2015-01-22 9:21 GMT+08:00 Ernesto Rivera <notifications@github.com>:

**Comment by jobpassion** [comment]
![image](https://cloud.githubusercontent.com/assets/5160106/5855197/7e9e5d14-a270-11e4-896a-09ffee64c4e3.png)

as the screenshot above, is the profiling with Instruments.
may be as you said, internal SDK caching/initialization took the place

**Comment by rivera-ernesto** [comment]
What I usually try is to:

* Profile in the simulator with a Release configuration. 
* Use the app normally repeating actions several times.
* "Simulate Memory Warning" in the Simulator. This will purge most internal caches and give you an idea of how well your app behaves.
