### ISSUE TITLE
Grey gradient background overlay app view after dismissing picker

### ISSUE THREAD

**Issue by DanH-SyncInteractive** [CyberAgent/iOS-NBUImagePicker#13]
I really love this picker but i'm having one issue that is a right pain.

iPhone 6 is 8.3

This happens on device and simulator.

Code:

```
NBUImagePickerOptions options = (
                                     NBUImagePickerOptionSingleImage |      // Single or multiple
                                     NBUImagePickerOptionReturnImages |     // Result Mode
                                     NBUImagePickerOptionStartWithPrompt |  // Start mode
                                     NBUImagePickerOptionDoNotSaveImages    // Save mode
                                     );
    [NBUImagePickerController startPickerWithTarget:self
                                            options:options
                                   customStoryboard:nil
                                        resultBlock:^(NSArray *imagesArray)
     {
         DebugLog(@"Count: %d", (int)imagesArray.count);
     }];
```

Steps to recreate:
1. Launch Picker, choose "Take a picture"
2. Press the Cancel button top left.
3. Picker dismisses, gradient overlay instantly added over top of screen. See screenshot.

![ios simulator screen shot 17 jun 2015 11 27 20](https://cloud.githubusercontent.com/assets/3983831/8204868/ddd8c694-14e3-11e5-96c8-d7d57effa4c7.png)

This only happens on the "Take a picture" option. "Choose an image" seems to be fine.

Thanks

**Comment by rivera-ernesto** [comment]
The demo project as committed here doesn't seem have that problem. Updating CocoaPods (committed here with 0.35.0) and GPUImage to check again.

**Comment by DanH-SyncInteractive** [comment]
So I have:
pod 'NBUImagePicker'

Which installs:
Installing GPUImage (0.1.6)
Installing Lockbox (2.1.0)
Installing MotionOrientation@PTEz (1.1.0)
Installing NBUCore (2.0.4)
Installing NBUImagePicker (1.5.3)
Installing NBUKit (2.4.1)
Installing RBVolumeButtons@PTEz (0.1.1)

When I download the demo project and run it, the issue doesn't occur. But I can't work out whats causing it in my project.

As I said, the choose library is fine. Its just take a photo.

**Comment by rivera-ernesto** [comment]
I'm pretty sure it's particular to your project. I suggest you trying to find out where that gradient view comes from by inspecting it with Xcode's UI Hierarchy tool.

http://www.raywenderlich.com/98356/view-debugging-in-xcode-6

**Comment by DanH-SyncInteractive** [comment]
Okay thanks for the info.

For reference I worked out what was causing the issue, incase anyone else stumbles on the same problem.

Essentially I was adding a gradient background view to my window as per the following code. Removing this fixed the issue... hoorah!

    UIView *bgView = [UIView new];
    [bgView setFrame:self.window.bounds];
    CAGradientLayer *lineGradientLayer = [CAGradientLayer layer];
    lineGradientLayer.frame = bgView.bounds;
    lineGradientLayer.colors = @[(id)[self.window.backgroundColor CGColor],
                                 (id)[[UIColor colorWithHexString:@"#4E5C6A"] CGColor]];
    lineGradientLayer.locations = @[@0.0, @1.0];
    [bgView.layer insertSublayer:lineGradientLayer atIndex:0];
    [self.window addSubview:bgView];
    [self.window sendSubviewToBack:bgView];

Thanks for the quick replies Rivera.

**Comment by rivera-ernesto** [comment]
Good to hear that! Thanks
