### ISSUE TITLE
NBUCoreImageFilterProvider [ciImage autoAdjustmentFilters]; No longer exists in iOS 9

### ISSUE THREAD

**Issue by DanH-SyncInteractive** [CyberAgent/iOS-NBUImagePicker#15]
NBUCoreImageFilterProvider.m 
```
+ (UIImage *)applyFilters:(NSArray *)filters
                  toImage:(UIImage *)image

NSArray * autoFilters = [ciImage autoAdjustmentFilters];

```

`autoAdjustmentFilters ` throws an error in the current XCode7 Beta. The function is now autoAdjustmentFiltersWithOptions

**Comment by rivera-ernesto** [comment]
It probably depends on what deployment iOS version you have. We may need to check for availability and choose which one to use.

**Comment by DanH-SyncInteractive** [comment]
This is iOS9

**Comment by rivera-ernesto** [comment]
As of iOS 8 `autoAdjustmentFilters` was not deprecated so I am pretty sure it does exist in iOS 9, maybe deprecated and throwing an error, but should exist.

Anyway feel free to submit a pull request using the `autoAdjustmentFiltersWithOptions:` which exists since iOS 5.

**Comment by DanH-SyncInteractive** [comment]
This is using the latest Xcode 7

**Comment by rivera-ernesto** [comment]
As I said, feel free to submit a pull request. I think using `autoAdjustmentFiltersWithOptions:` should work with al versions.

**Comment by riksof-abdulrauf** [comment]
Hi,
How can I get the new Apple default filters in 

    // Get only the core image filters.
    NSArray *filterTypes = [NBUFilterProvider availableFilters];

**Comment by rivera-ernesto** [comment]
You can execute this commented [code](https://github.com/CyberAgent/iOS-NBUImagePicker/blob/e16cbc7f4d5d10da422190ee2d51d61d6ed31b00/Source/Filters/NBUCoreImageFilterProvider.m#L28).

Also we would need to add new filters to that same file. Please create a new issue to discuss this.

**Comment by almoehi** [comment]
are you planning to publish an updated cocoapod including this fix?
It's basically blocking all developments on xcode 7.3 / iOS9 ...

**Comment by rivera-ernesto** [comment]
Sadly I am not actively using the library but it would be great to have a pull request to fix that.
